### PR TITLE
No fork

### PR DESCRIPTION
**Pull request by nevakrien**
added a posit-spawn mode to allow for better resource use in no over commit environment.
this could also be implemented with clone if preferred just let me know

### CODE REVIEW

**Comment by Neko-Box-Coder** [comment]
Thanks, I will take a look tomorrow and add commits for formatting, returning error codes and readme.
Implementation seems good to me.
I will keep #3 open even after merging this so that I can come back to it in the future.

**Comment by Neko-Box-Coder** [comment]
I have just tidied up the branch.

It seems like `posix_spawn()` is actually using `vfork()` under the hood anyway which means it **could** suspend the caller :joy: . But it didn't suspend it from my test :shrug: so I will probably still merge it and have it as an option.

Anyway `posix_spawn()` is probably the safer option than `vfork()` since we could accidentally modify the caller memory.

I was testing with `malloc()` and I couldn't really observe the over-commitment with `btop` or `htop`. How did it come up on your use case?

**Comment by nevakrien** [comment]
i think its vfork on linux but not apple which is the big deal. like on apple its not glibc its the clang lib so it should not do the annoying thing unless someone is using gcc on apple which is weird behivior. If this is still an issue we could add a check for if this is on apple with a new gcc and if thats the case throw a warning or an error.

the main upside for the posix version is that it works on bsd and other unix systems that are not linux so purely as a portability thing its a good idea since it gives any OS the potential to implement things correctly.

also the more i looked at it the more i think clone can potentially work. I cant get a straight official answer to what happens when you clone on the parent process then unmap the childs stack. if the answer is that it unmaps the stack from the PARENT but the childs space stays mapped then using clone mmap and munmap would solve this on all linux. 

it also adds another layer of robustness since it keeps the stack-size constant on all commands instead of depending on the stacksize from when we called. and we get to do changedir again so no missing features which is very nice. so if i manage to find anything would test.

**Comment by nevakrien** [comment]
as to how overcommit works you need to [set something in the kernel ](https://serverfault.com/questions/485798/cent-os-how-do-i-turn-off-or-reduce-memory-overcommitment-and-is-it-safe-to-do)so that it forbids overcommit. or rather thats the only time overcommit is an issue.

if you dont then linux is actually very effishent and handles this beautifully the issue is only if you are on a very big process on a machine that has overcommit turned off or if you do something like ulimit then for a breif period between fork and execv the memory of the parent process is counted twice towards the total memory usage. even tho it is not backed up by anything phisical and wont be an issue.

seems like a very contrived situation honestly but ik on server environments that need to be reliable people turn off overcommit  hence why I care. didnt ran into it on my machine because I have 128gb of ram but if its important I can do some testing on the existing pull request and see the diffrence. I think using ulimit should make this farely straight forward and I could make a small test you could run as well.

**Comment by Neko-Box-Coder** [comment]
Yeah, your reason makes sense. 

I think I will keep the current solution. This is just a temporary patch anyway. 

I will probably come back to this at some point with a proper solution which is just do a `fork()` at the beginning to act as a daemon. And use pipes to communicate with the daemon for it to perform `fork()` for the commands.

Take a look at the current changes and see if I need to add/change anything. If not I can merge it.

**Comment by nevakrien** [comment]
LGTM if you tested it and it worked then its fine. 
forking in the start is probably the way to go. probably as a feature flag as well.

sidenote: it would be fairly neat to add some tests, it would act as a form of documentation as well. I feel like a few extra examples could really help.

**Pull request merged**
